server:
  port: 10002
#  application:
#    name: order
mybatis:
  mapper-locations: "classpath*:mapper/*Mapper.xml"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  ##配置队列
spring:
  rabbitmq:
    host: 192.168.118.130
    port: 5672
    username: guest
    password: guest
    
girl:
  name: yangsi
  age:18


