server:
  port: 10001
eureka:
  instance:
    hostname: product
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
#  instance:
#    hostname: product
spring:
  rabbitmq:
    host: 192.168.118.130
    port: 5672
    username: guest
    password: guest
