server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: product
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
#  instance:
#    hostname: product
